import Problems.Zeta2.Ferguson
import Problems.Zeta2.Certificates
import Problems.Zeta2.Irrationality
import Problems.Zeta3.Ferguson
import Problems.Zeta3.Certificates
import Problems.Zeta3.Irrationality
import Problems.Zeta5.Ferguson
import Problems.Zeta5.Certificates
import Problems.Zeta5.Irrationality
import Problems.Zeta7.Ferguson
import Problems.Zeta7.Certificates
import Problems.Delta.Ferguson
import Problems.Delta.Certificates
import Problems.Delta.Irrationality
import Problems.Gamma.Ferguson
import Problems.Gamma.Certificates
import Problems.Gamma.Irrationality
import Problems.Catalan.Ferguson
import Problems.Catalan.Certificates
import Problems.Catalan.Irrationality
import Problems.L2ChiMinus3.Ferguson
import Problems.L2ChiMinus3.Irrationality
