import LeanProve.Certificate
import Problems.Catalan.Ferguson

/-!
Auto-generated by `export-lean-certificates`.
Do not edit by hand. Re-run:

```bash
cargo run --release -p hs-problems --bin export-catalan-certificates
```
-/


namespace Problems.Catalan
open Hankel Ferguson

def certificates : List LeanProve.FergusonCertificate := [
  ⟨0, 1, 16, 3, 16, 16, 1, 3⟩,
  ⟨1, 5, 12288, 89, 82944, 331776, 135, 356⟩,
  ⟨2, 505319, 4299816960000, 11879, 39813120000, 4299816960000, 505319, 1282932⟩,
  ⟨3, 53500697, 29365647704064000000, 7733213, 1699400908800000000, 734141192601600000000, 1337517425, 3340748016⟩,
  ⟨4, 26920197674520019, 16653452508786950406144000000000000, 6172998714751, 1541986343406199111680000000000, 16653452508786950406144000000000000, 26920197674520019, 66668386119310800⟩,
]

def certificate (n : Nat) : Option LeanProve.FergusonCertificate :=
  certificates.find? (·.n = n)

theorem certificates_nonempty : certificates ≠ [] := by
  decide

end Problems.Catalan
