import LeanProve.Certificate
import Problems.Zeta7.Ferguson

/-!
Auto-generated by `export-lean-certificates`.
Do not edit by hand. Re-run:

```bash
cargo run --release -p hs-problems --bin export-zeta7-certificates
```
-/


namespace Problems.Zeta7
open Hankel Ferguson

def certificates : List LeanProve.FergusonCertificate := [
  ⟨0, 1, 1, 127, 128, 128, 128, 127⟩,
  ⟨1, 1567861, 4586471424, 3400548985, 10030613004288, 10030613004288, 3428912007, 3400548985⟩,
  ⟨2, 643278902612699435821347431, 614094221446481549721600000000000000, 291702224443155228623467, 280792968196836556800000000000000, 614094221446481549721600000000000000, 643278902612699435821347431, 637952764857180484999522329⟩,
]

def certificate (n : Nat) : Option LeanProve.FergusonCertificate :=
  certificates.find? (·.n = n)

theorem certificates_nonempty : certificates ≠ [] := by
  decide

end Problems.Zeta7
