import LeanProve.Certificate
import Delta.Ferguson

/-!
Auto-generated by `export-lean-certificates`.
Do not edit by hand. Re-run:

```bash
cargo run --release -p hs-problems --bin export-delta-certificates
```
-/


namespace Delta
open Hankel Ferguson

def certificates : List LeanProve.FergusonCertificate := [
  ⟨0, 1, 1, 2, 1, 1, 1, 2⟩,
  ⟨1, 4, 1, 7, 1, 1, 4, 7⟩,
  ⟨2, 80, 1, 136, 1, 1, 80, 136⟩,
  ⟨3, 17856, 1, 30096, 1, 1, 17856, 30096⟩,
  ⟨4, 76308480, 1, 128231424, 1, 1, 76308480, 128231424⟩,
]

def certificate (n : Nat) : Option LeanProve.FergusonCertificate :=
  certificates.find? (·.n = n)

theorem certificates_nonempty : certificates ≠ [] := by
  decide

end Delta
