use crate::certificate::FergusonCertificate;
use crate::export::CertificateExport;
use crate::rational::ratio_to_lean_ints;
use std::fmt::Write as _;

/// Render a Lean module containing certificate data.
pub fn render_certificates(config: &CertificateExport, rows: &[FergusonCertificate]) -> String {
    let mut out = String::new();
    writeln!(out, "import {}", config.certificate_module).expect("write import");
    writeln!(out, "import {}", config.ferguson_module).expect("write ferguson import");
    writeln!(out).expect("write blank");
    writeln!(
        out,
        "/-!\nAuto-generated by `{}`.\nDo not edit by hand. Re-run:\n\n```bash\n{}\n```\n-/\n",
        config.generator, config.regenerate_cmd
    )
    .expect("write header");
    writeln!(out).expect("write blank");
    writeln!(out, "namespace {}", config.namespace).expect("write namespace");
    writeln!(out, "open {}", config.open_namespaces).expect("write open");
    writeln!(out).expect("write blank");
    writeln!(
        out,
        "def {} : List {} := [",
        config.list_name, config.certificate_type
    )
    .expect("write list");
    for row in rows {
        write_row(&mut out, row);
    }
    writeln!(out, "]").expect("write list end");
    writeln!(out).expect("write blank");
    writeln!(
        out,
        "def certificate (n : Nat) : Option {} :=\n  {}.find? (·.n = n)",
        config.certificate_type, config.list_name
    )
    .expect("write lookup");
    writeln!(out).expect("write blank");
    writeln!(
        out,
        "theorem {}_nonempty : {} ≠ [] := by\n  decide",
        config.list_name, config.list_name
    )
    .expect("write theorem");
    writeln!(out).expect("write blank");
    writeln!(out, "end {}", config.namespace).expect("write end");
    out
}

fn write_row(out: &mut String, row: &FergusonCertificate) {
    let (p_num, p_den) = ratio_to_lean_ints(&row.p);
    let (q_num, q_den) = ratio_to_lean_ints(&row.q);
    writeln!(
        out,
        "  ⟨{}, {}, {}, {}, {}, {}, {}, {}⟩,",
        row.n, p_num, p_den, q_num, q_den, row.scaled.scale, row.scaled.int_p, row.scaled.int_q
    )
    .expect("write row");
}
