/-!
Auto-generated by `export-lean-certificates`.
Do not edit by hand. Re-run:

```bash
cargo run --release -p zeta-2 --bin export-zeta2-certificates
```
-/

import LeanProve.Certificate
import Zeta2.Ferguson

namespace Zeta2
open Hankel Ferguson

def certificates : List LeanProve.FergusonCertificate := [
  ⟨0, 1, 1, 3, 4, 4, 4, 3⟩,
  ⟨1, 5, 192, 89, 5184, 5184, 135, 89⟩,
  ⟨2, 505319, 16796160000, 11879, 622080000, 16796160000, 505319, 320733⟩,
  ⟨3, 53500697, 28677390336000000, 7733213, 6638284800000000, 716934758400000000, 1337517425, 835187004⟩,
  ⟨4, 26920197674520019, 4065784303903064064000000000000, 6172998714751, 1505846038482616320000000000, 4065784303903064064000000000000, 26920197674520019, 16667096529827700⟩,
]

def certificate (n : ℕ) : Option LeanProve.FergusonCertificate :=
  certificates.find? (·.n = n)

theorem certificates_nonempty : certificates ≠ [] := by
  decide

end Zeta2
